### ISSUE TITLE
logRecord项目本地maven打包后，不能被springboot项目扫到bean

### ISSUE THREAD

**Issue by migaoyang** [qqxx6661/logRecord#1]
![image](https://user-images.githubusercontent.com/44117973/142176864-d6d6a021-82fa-4858-9063-e7bf6b74f0df.png)

Field logService in cn.monitor4all.logRecord.aop.SystemLogAspect required a bean of type 'cn.monitor4all.logRecord.service.LogService' that could not be found.

**Comment by qqxx6661** [comment]
你拉的版本是不是release v1.0.0的？我昨天在接入rocketMq，上传了个可能没有配置好的commit，所以可能会有这个问题。我今天push了两个commit，现在最新的版本是0350ac6d0b0f7df471068a11927d32f0778af9fb，你可以拉一下master最新的。应该是ok啦

**Comment by qqxx6661** [comment]
现在master支持了rocket和rabbitmq，具体配置的meta文件我还没有写全。你可以先参考下这个：

```
# log-record 配置
log-record.data-pipeline=rocketMq

log-record.rabbit-mq-properties.host=localhost
log-record.rabbit-mq-properties.port=5672
log-record.rabbit-mq-properties.username=admin
log-record.rabbit-mq-properties.password=xxxxxx
log-record.rabbit-mq-properties.queue-name=logRecord
log-record.rabbit-mq-properties.routing-key=
log-record.rabbit-mq-properties.exchange-name=logRecord

log-record.rocket-mq-properties.topic=logRecord
log-record.rocket-mq-properties.tag=
log-record.rocket-mq-properties.group-name=logRecord
log-record.rocket-mq-properties.namesrv-addr=localhost:9876
```

**Comment by migaoyang** [comment]
> 现在master支持了rocket和rabbitmq，具体配置的meta文件我还没有写全。你可以先参考下这个：
> 
> ```
> # log-record 配置
> log-record.data-pipeline=rocketMq
> 
> log-record.rabbit-mq-properties.host=localhost
> log-record.rabbit-mq-properties.port=5672
> log-record.rabbit-mq-properties.username=admin
> log-record.rabbit-mq-properties.password=xxxxxx
> log-record.rabbit-mq-properties.queue-name=logRecord
> log-record.rabbit-mq-properties.routing-key=
> log-record.rabbit-mq-properties.exchange-name=logRecord
> 
> log-record.rocket-mq-properties.topic=logRecord
> log-record.rocket-mq-properties.tag=
> log-record.rocket-mq-properties.group-name=logRecord
> log-record.rocket-mq-properties.namesrv-addr=localhost:9876
> ```

**Comment by migaoyang** [comment]
好嘞 感谢大佬
