### ISSUE TITLE
局部变量有没有优雅方式记录到日志里

### ISSUE THREAD

**Issue by SpringStudent** [qqxx6661/logRecord#14]
大佬你好，感谢提供了这么优秀的日志记录框架
![image](https://user-images.githubusercontent.com/14833956/179926859-974918cf-7d25-474d-8680-f5230f3a1417.png)
我日志中需要记录的bizId是方法中的局部变量，除了通过LogRecordContext.putVariables("id", id)，使用函数的spel表达式看样子不太行。

**Comment by qqxx6661** [comment]
如果是局部变量，确实没有非常优雅的方式。看你的代码，除了用`LogRecordContext.putVariables("id", id)`之外，有几个思路：

1. 把方法返回值设置为id或者Account实体，这样可以通过#_return或者#_return.id拿到返回值里的属性。（副作用：修改了原方法的定义）
2. 用自定义函数，比如`bizId="#queryAccountByUserName(#username)"`, 不过这样有点本末倒置，为了优雅而优雅了，而且还得保证username是唯一的才行。

我建议是用1比较好。或者有什么更好的办法，在框架层面做改动，暂时还没想到 ：）

**Comment by SpringStudent** [comment]
感谢大佬的回复，综合考量下来我还是采用了方式2，方式1我当时也想到过，但是考虑到每个同事不可能为了记录日志而去修改方法签名暂且不采纳。
