### ISSUE TITLE
CustomFunctionObjectDiff 组件取newData alias使用的是oldObject

### ISSUE THREAD

**Issue by yanming16** [qqxx6661/logRecord#15]
CustomFunctionObjectDiff 类里第54行
            // 对象类名
51        String oldClassName = oldObject.getClass().getName();
52        String newClassName = newObject.getClass().getName();
53        LogRecordDiff oldClassLogRecordDiff = oldObject.getClass().getDeclaredAnnotation(LogRecordDiff.class);
54        LogRecordDiff newClassLogRecordDiff = oldObject.getClass().getDeclaredAnnotation(LogRecordDiff.class);

**Comment by qqxx6661** [comment]
还真是，感谢。我改一下

**Comment by qqxx6661** [comment]
已修复于1.2.1版本
