### ISSUE TITLE
关于DIFF

### ISSUE THREAD

**Issue by MrChenshen** [qqxx6661/logRecord#16]
作者你好，使用DIFF的时候需要从业务代码中获取原来的值，这个还有调整的空间吗

**Comment by qqxx6661** [comment]
能举个具体例子么，现在DIFF新老对象都可以指定为 从业务代码中传递

**Comment by MrChenshen** [comment]
意思是DIFF中老对象的指定可以像参数一样支持函数么，不然只能从业务代码从传递了

**Comment by qqxx6661** [comment]
> 意思是DIFF中老对象的指定可以像参数一样支持函数么，不然只能从业务代码从传递了

我理解是可以的。

`msg = "#_DIFF(#request.old, #request.new)"`

类似这种直接从参数中拿也是支持的。都在一个上下文里。

**Comment by MrChenshen** [comment]
好的，谢谢作者
