### ISSUE TITLE
说明文档里diffDTOList数组为什么同样的数据存储两条，没理解

### ISSUE THREAD

**Issue by swmwlm** [qqxx6661/logRecord#18]
testService.testObjectDiff(new TestUser(2, "李四"));

===========================
"diffDTOList":[
    {
      "diffFieldDTOList":[
        {
          "fieldName":"id",
          "newFieldAlias":"用户工号",
          "newValue":2,
          "oldFieldAlias":"用户工号",
          "oldValue":1
        },
        {
          "fieldName":"name",
          "newValue":"李四",
          "oldValue":"张三"
        }],
      "newClassAlias":"用户信息实体",
      "newClassName":"cn.monitor4all.logRecord.test.bean.TestUser",
      "oldClassAlias":"用户信息实体",
      "oldClassName":"cn.monitor4all.logRecord.test.bean.TestUser"
    },
    {
      "diffFieldDTOList":[
        {
          "fieldName":"id",
          "newFieldAlias":"用户工号",
          "newValue":2,
          "oldFieldAlias":"用户工号",
          "oldValue":1
        },
        {
          "fieldName":"name",
          "newValue":"李四",
          "oldValue":"张三"
        }],
      "newClassAlias":"用户信息实体",
      "newClassName":"cn.monitor4all.logRecord.test.bean.TestUser",
      "oldClassAlias":"用户信息实体",
      "oldClassName":"cn.monitor4all.logRecord.test.bean.TestUser"
    }]

**Comment by qqxx6661** [comment]
只是想标明diffDTOList是个list，里面有多个值。没有其他含义。

一次注解中，用户可能会多次使用_DIFF()函数，所以可能会有多对对象进行比较。

**Comment by swmwlm** [comment]
> 只是想标明diffDTOList是个list，里面有多个值。没有其他含义。
> 
> 一次注解中，用户可能会多次使用_DIFF()函数，所以可能会有多对对象进行比较。

但是，我运行您的测试用例，确实此list包涵了两个相同的数据。是不是有重复调用了

**Comment by qqxx6661** [comment]
> > 只是想标明diffDTOList是个list，里面有多个值。没有其他含义。
> > 一次注解中，用户可能会多次使用_DIFF()函数，所以可能会有多对对象进行比较。
> 
> 但是，我运行您的测试用例， testService.testObjectDiff(new TestUser(2, "李四")); 确实此list包涵了两个相同的数据。是不是有重复调用了

我看了下，我是这么写的

`@OperationLog(bizId = "'1'", bizType = "'testObjectDiff'", msg = "#_DIFF(#oldObject, #testUser)", extra = "#_DIFF(#oldObject, #testUser)")`

msg和extra里都写了_DIFF，所以等于是一个注解有两次相同对象的diff了，正常情况不太会这么写，我当时应该是想着测试下diffDTOList是否能正确生成两个。测试类写的有点潦草，之后可以优化下。

**Comment by swmwlm** [comment]
好的，谢谢，明白了
