### ISSUE TITLE
使用diff场景问题

### ISSUE THREAD

**Issue by swmwlm** [qqxx6661/logRecord#19]
实际业务中，当修改的对象是复杂对象，里面又包含List对像集合，这种情况时支持吗？我自测没通过

**Comment by qqxx6661** [comment]
> 实际业务中，当修改的对象是复杂对象，里面又包含List对像集合，这种情况时支持吗？我自测没通过

目前仅支持单层，基础类型的DIFF，嵌套等类型，还没开发，暂时不支持。

可以考虑写一个新的SpEL自定义函数，将参数传入后自定义函数，调用第三方diff库，拿到结果返回。这样可以拐一个弯支持复杂对象的diff。
