### ISSUE TITLE
解析spel自定义函数

### ISSUE THREAD

**Issue by Durianyang** [qqxx6661/logRecord#2]
有打算添加spel对自定义函数解析的内容吗

**Comment by qqxx6661** [comment]
我看看哈，正在考虑之后先做点什么改进，毕竟精力有限。自定义函数，能举个具体的使用场景么？

**Comment by qqxx6661** [comment]
自定义函数应该是spEL默认的支持？我的切面好像拿到的是做完函数后值

**Comment by qqxx6661** [comment]
v1.0.4已经支持，欢迎试用。
