### ISSUE TITLE
LogRecordDiff实体差异记录的时候，如果有属性有类或者list<Object>，里面就不仔细比较了，而且也没展示别名。很多情况下都是一对一或者一对多的实体关系呀

### ISSUE THREAD

**Issue by compellingBug** [qqxx6661/logRecord#20]

**Comment by compellingBug** [comment]
例如如下：testClass2s，再深一层的属性怎么整，作者能否完善一下呀 
"diffDTOList":[
            {
                "diffFieldDTOList":[
                    {
                        "fieldName":"testStr",
                        "newFieldAlias":"测试字符串",
                        "newValue":"啊啊啊啊啊啊啊啊啊",
                        "oldFieldAlias":"测试字符串",
                        "oldValue":"哈哈哈哈哈哈哈哈哈"
                    },
                    {
                        "fieldName":"testClass2s",
                        "newFieldAlias":"测试内部实体",
                        "newValue":{
                            "userPassword":"123456",
                            "username":"胖大叔"
                        },
                        "oldFieldAlias":"测试内部实体",
                        "oldValue":{
                            "userPassword":"123456",
                            "username":"帅小伙"
                        }
                    }
                ],
                "newClassAlias":"测试信息实体",
                "newClassName":"cn.monitor4all.logrecordwebdemo.domain.TestClass3",
                "oldClassAlias":"测试信息实体",
                "oldClassName":"cn.monitor4all.logrecordwebdemo.domain.TestClass3"
            }
        ]

**Comment by qqxx6661** [comment]
是的，暂时只写完单层基础类型的DIFF，数组，嵌套类型等还没有写完。 :(

如果急的话，可以使用自定义函数，然后自己调用第三方库对比两个对象，然后拿到第三方库的结果，写到LogRecordContext或者JSON后作为自定义函数的返回，类似之前这个issue #19

**Comment by qqxx6661** [comment]
这样等于是用第三方能力了，也比较灵活一些，DIFF支持也会更全

**Comment by qqxx6661** [comment]
v1.3.1版本对DIFF进行了一定改动：目前DIFF功能支持完全不同的类之间进行DIFF，对于同名的基础类型，进行equals对比，对于同名的非基础类型，则借用fastjson的toJSON能力，转为JSONObject进行对比，本质上是将对象映射为map进行map.equals。
