### ISSUE TITLE
找不到依赖

### ISSUE THREAD

**Issue by MWorld2021** [qqxx6661/logRecord#3]
配置了github生效后，依赖仍爆红。`Could not find artifact cn.monitor4all:log-record-starter:pom:1.0.0 in central (https://repo1.maven.org/maven2)`

**Comment by qqxx6661** [comment]
我的依赖之前不支持中央仓库的，前两天我搞定了，现在你在这个中央仓库也能拉到了。把版本号换成1.0.1

```
<dependency>
    <groupId>cn.monitor4all</groupId>
    <artifactId>log-record-starter</artifactId>
    <version>1.0.1</version>
</dependency>
```
